name: Docker Image CI

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mja-71/library/ubuntu_qt_dev:1.0

on:
  push:
    branches: 
    - 'main'
    - 'release/**'
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
